
services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_management
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis_cache:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    depends_on:
      - postgres_db
      - redis_cache
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    command: ["npm", "run", "start"]

volumes:
  pg_data:
